/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/Address.vue')['default']
    ClientProfile: typeof import('./src/components/ClientProfile.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    MainContact: typeof import('./src/components/MainContact.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteAddress: typeof import('./src/components/SiteAddress.vue')['default']
    Sites: typeof import('./src/components/Sites.vue')['default']
    SitesTable: typeof import('./src/components/SitesTable.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
